name: Presubmit.ai

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  pull_request_target:
    types: [opened, synchronize]
  pull_request_review_comment:
    types: [created]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Check required secrets
        run: |
          if [ -z "${{ secrets.SAP_AI_CORE_CLIENT_SECRET }}" ]; then
            echo "Error: SAP_AI_CORE_CLIENT_SECRET secret is not configured"
            exit 1
          fi
      - uses: ncryptedV1/ai-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLM_MODEL: "anthropic--claude-3.7-sonnet"
          LLM_PROVIDER: "sap-ai-sdk"
          SAP_AI_CORE_CLIENT_ID: ${{ secrets.SAP_AI_CORE_CLIENT_ID }}
          SAP_AI_CORE_CLIENT_SECRET: ${{ secrets.SAP_AI_CORE_CLIENT_SECRET }}
          SAP_AI_CORE_TOKEN_URL: ${{ vars.SAP_AI_CORE_TOKEN_URL }}
          SAP_AI_CORE_BASE_URL: ${{ vars.SAP_AI_CORE_BASE_URL }}
          GITHUB_API_URL: "https://api.github.com"
          GITHUB_SERVER_URL: "https://github.com"
